name: Test

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
          cache: false

      - name: Run tests
        run: go test -v ./test/integration/integration_test
